export const PLAN_CATALOG = [
  {
    code: 'one_time',
    title: '⚡ Разовый доступ',
    short: 'Для быстрого теста',
    posts: 1,
    themes: 1,
    ideaRegen: 0,
    textRegen: 0,
    price: 99,
    highlight: false,
  },
  {
    code: 'plan10',
    title: '📌 10 постов',
    short: 'Старт для регулярного контента',
    posts: 10,
    themes: 10,
    ideaRegen: 2,
    textRegen: 3,
    price: 590,
    highlight: false,
  },
  {
    code: 'plan15',
    title: '⭐ 15 постов (Рекомендуем)',
    short: 'Оптимальный баланс цены и возможностей',
    posts: 15,
    themes: 20,
    ideaRegen: 5,
    textRegen: 5,
    price: 790,
    highlight: true,
  },
  {
    code: 'plan30',
    title: '🚀 30 постов',
    short: 'Для стабильного контент-потока',
    posts: 30,
    themes: 40,
    ideaRegen: 10,
    textRegen: 10,
    price: 1290,
    highlight: false,
  },
  {
    code: 'unlim',
    title: '⚡ Безлимит',
    short: 'Максимум свободы и экспериментов',
    posts: 100,
    themes: 100,
    ideaRegen: 100,
    textRegen: 100,
    price: 2490,
    highlight: false,
  },
];

export const PLAN_MAP = new Map(PLAN_CATALOG.map((plan) => [plan.code, plan]));
